config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  
  #root route
  root   'login#welcome'

  # user route start
  get '/users', to: 'users#index'
  get '/users/new' => 'users#new', as: 'new_user'
  post '/users'    => 'users#create', as: 'create_user'
  get  '/users/:id' => 'users#show', as: 'show_user'
  get '/users/:id/edit ' => 'users#edit', as: 'edit_user'
  patch '/users/:id'   => 'users#update', as: 'update_user'
  delete '/users/:id' => 'users#destroy', as: 'delete_user'
  # user route end

  #login routes start
  get    '/login'  => 'login#new'
  post   '/login'  => 'login#create', as: 'login_user'
  get    '/index'  => 'login#welcome'
  get    '/signup/new' => 'login#signupnew', as: 'login_user_signup'
  post    '/signup' => 'login#signupcreate', as: 'create_login_user' 
  delete '/logout' => 'login#delete', as: 'logout_user'
  #login routes end

  #author routes start
  get '/authors' => 'authors#index'
  get '/authors/new' => 'authors#new',  as: 'new_author'
  post '/authors' => 'authors#create',   as: 'create_author'  
  get '/authors/:id' => 'authors#show', as: 'show_author'
  get '/authors/:id/edit' => 'authors#edit', as: 'edit_author'
  patch '/authors/:id' => 'authors#update', as: 'update_author'
  delete '/authors/:id' => 'authors#destroy', as: 'delete_author'
  #author routes end

  #quotes routes start
  get '/authors/:author_id/quotes' => 'quotes#index', as: 'authors_quotes'
  get '/authors/:author_id/quotes/new' => 'quotes#new',  as: 'new_author_quotes'
  post '/authors/:author_id/quotes' => 'quotes#create',  as: 'create_author_quotes' 
  get '/authors/:author_id/quotes/:id' => 'quotes#show', as: 'show_author_quotes'
  get '/authors/:author_id/quotes/:id/edit' => 'quotes#edit', as: 'edit_author_quotes'
  patch '/authors/:author_id/quotes/:id' => 'quotes#update', as: 'update_author_quotes'
  delete '/authors/:author_id/quotes/:id' => 'quotes#destroy', as: 'delete_author_quotes'
  #quotes routes end

  #tag routes start
  get '/tag' => 'tags#index', as: 'tag'
  get '/tag/new' => 'tags#new',  as: 'new_tag'
  post '/tag' => 'tags#create',  as: 'create_tag' 
  get '/tag/:id' => 'tags#show', as: 'show_tag'
  get '/tag/:id/edit' => 'tags#edit', as: 'edit_tag'
  patch '/tag/:id' => 'tags#update', as: 'update_tag'

  delete '/tag/:id' => 'tags#destroy', as: 'delete_tag'
  #tag routes end

end

app/models/quote.rb
class Quote < ApplicationRecord
  belongs_to :author
  has_many :quotation_tags
  has_many :tags,:through => :quotation_tags, dependent: :destroy   
  
end

app/controllers/quotes_controller.rb
class QuotesController < ApplicationController
    def index
        @author = Author.where(id: params[:author_id])
        @quotes = Quote.where(author_id: params[:author_id])
        @get_tag  = Tag.all    
    end 
   
    def new
        @quote = Quote.new
    end

    def create
        @quote = Quote.new(quote_params)
        if  @quote.save 
            redirect_to authors_quotes_path
        else
            flash[:errors] = @quote.errors.full_messages 
            redirect_to new_author_quotes_url   
        end  
    end 

    def show
        @quotes = Quote.find(params[:id])
    end

    def edit
        if is_admin? 
            @quotes = Quote.find(params[:id])
            @author = Author.find(params[:author_id])
        else   
            flash[:errors] = "You are not Authorized to that!"
            redirect_to authors_quotes_path
        end
    end  

    def update
        @quotes = Quote.find(params[:id])
        @author = Author.find(params[:author_id])  
        if @quotes
            @quotes.update(quote_params)     
            @author.update(params.permit(:author_name))
            redirect_to authors_quotes_path
        else
            flash[:errors] = @articles.errors.full_messages 
            redirect_to show_author_quotes_path
        end

    end 

    def destroy
        @quotes = Quote.find(params[:id])
        if @quotes
            @quotes.destroy                
            redirect_to authors_quotes_url
        end 
    end

    private
    def quote_params
        params.permit(:description, :author_id, tag_ids: []) 
    end

end 

app/helpers/quotes_helper.rb
module QuotesHelper
end

app/views/quotes/edit.html.erb
<% if flash[:errors]%>
        <div class="alert alert-danger" role="alert">
                <%= flash[:errors]%>
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                <span aria-hidden="true">&times;</span>
            </button>
        </div>
<%end%>

<div class="container mt-5 mr-5">
    <div class="col-md-6 mb-4">
        <div class="card">
            <div class="card-body">
                 <%= form_tag update_author_quotes_path(@quotes.author_id, @quotes.id), method: :patch do %>
                         <h3 class="text-center font-bold py-4"><strong>Edit Quote</strong></h3>
                            <div class="input-group mb-3">
                                    <div class="input-group-prepend">
                                          <span class="input-group-text" id="inputGroup-sizing-default"><i class="fas fa-pen"></i></span>
                                    </div>  
                                    <%= text_field_tag  :description, @quotes.description ,class: "form-control" %>                  
                            </div>

                            <div class="input-group mb-3">
                                    <div class="input-group-prepend">
                                          <span class="input-group-text" id="inputGroup-sizing-default"><i class="fas fa-user"></i></span>
                                    </div>  
                                     <%= text_field_tag  :author_name, @author.author_name ,class: "form-control" %>                                            
                            </div>
                                <% Tag.all.each do |t| %>
                                    <%= check_box_tag 'tag_ids[]' ,t.id,@quotes.tag_ids.include?(t.id),include_hidden: false  %>
                                    <%= t.name %>
                                    <br/>
                                <% end %>

                            <div class="text-center py-4">
                                <%= submit_tag "Update Quote", class: "btn btn-primary" %>
                            </div>
                 <%end%>                       
            </div>
        </div>
    </div>
</div>

app/views/quotes/index.html.erb
<%= stylesheet_link_tag "quotes", media: "all", "data-turbolinks-track" => "reload" %>
 
<% if flash[:errors]%>
        <div class="alert alert-warning" role="alert">
                <%= flash[:errors] = "You are not Authorized to that!"%>
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                <span aria-hidden="true">&times;</span>
            </button>
        </div>
<%end%>




 <div class="jumbotron">
    <h1 class="display-4">Quotes Section</h1>
    <p class="lead">Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.</p>
    <p>Ut enim ad minim veniam,quis nostrud exercitation ullamco laboris nisi ut. </p>                      
        <% if is_admin? %> 
            <%= button_to  "Add New Quotes",new_author_quotes_path,  :class => "btn btn-primary btn-md",method: :get%>   
        <%end%>
</div>

<div class="row">
  <% @quotes.each do |quote| %>
  <div class="col-sm-4">
    <div class="card w-70  ml-5 mr-5 mb-5 mt-2 bg-light border-dark ">
            <div class="card-body">
                <blockquote class="blockquote">
                    <p class="card-text "><%= link_to quote.description,
                    edit_author_quotes_path(quote.author_id,quote.id) %></p>                
                   <%@get_tag.each do |tag| %>
                            <a class="card-subtitle mb-2 text-muted">#<%= tag.name%></a>
                     <%end%>  
                    <footer class="blockquote-footer">
                        <small>
                            <% @author.each do |author| %>
                                 <cite title="Source Title"><%= author.author_name%></cite>
                            <%end%>
                        </small>
                    </footer>

                    <% if is_admin? %>
                        <div class="text-right">
                            <%= link_to "Delete", delete_author_quotes_path(quote.author_id, quote.id), :class => "btn btn-danger btn-sm mt-2" ,method: :delete%>                                                
                        </div>
                    <% end %>    
                </blockquote>
            </div>   
             <div class="card-footer">                 
               <small class="text-muted">Last updated 3 mins ago</small>
            </div>
         </div>
     </div>
   <%end%>
</div>

app/views/quotes/new.html.erb
   <%# <%= form_tag create_author_quotes_path do %> 
     
        <%# <%= label_tag :description%>
        <%# <%= text_area_tag :description%> 
  
   <%# <%= submit_tag "Add"%> 
<%# <%end%>


<% if flash[:errors]%>
    <% flash[:errors].each do |error| %>
        <div class="alert alert-danger" role="alert">
                <%= error%>
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                <span aria-hidden="true">&times;</span>
            </button>
        </div>
    <% end %>
<%end%>

<div class="container mt-5 mr-5">
    <div class="col-md-6 mb-4">
        <div class="card">
            <div class="card-body">
                 <%= form_tag create_author_quotes_path do %>
                         <h3 class="text-center font-bold py-4"><strong>Create New Quote</strong></h3>
                                <div class="input-group mb-3">
                                        <div class="input-group-prepend">
                                             <span class="input-group-text" id="inputGroup-sizing-default"><i class="fas fa-user"></i></span>
                                        </div>
                                            <%= text_field_tag  :description, nil,placeholder: 'Enter Quote...',class: "form-control" %>                  
                                </div>                                  
                                <% Tag.all.each do |t| %>
                                    <%= check_box_tag 'tag_ids[]' ,t.id, checked = false,include_hidden: false  %>
                                    <%= t.name %>
                                <br />
                                <% end %>
                                <div class="text-center py-4">
                                    <%= submit_tag "Create Quote", class: "btn btn-primary" %>
                                </div>
                 <%end%>         
            </div>
        </div>
    </div>
</div>

app/views/quotes/show.html.erb
<h1>Show Quotes Page</h1>


<%= button_to "Edit Quotes", edit_author_quotes_path(@quotes), method: :get%>

<h2>Quotes Description <%= @quotes.description %></h2>