config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  
  #root route
  root   'login#welcome'

  # user route start
  get '/users', to: 'users#index'
  get '/users/new' => 'users#new', as: 'new_user'
  post '/users'    => 'users#create', as: 'create_user'
  get  '/users/:id' => 'users#show', as: 'show_user'
  get '/users/:id/edit ' => 'users#edit', as: 'edit_user'
  patch '/users/:id'   => 'users#update', as: 'update_user'
  delete '/users/:id' => 'users#destroy', as: 'delete_user'
  # user route end

  #login routes start
  get    '/login'  => 'login#new'
  post   '/login'  => 'login#create', as: 'login_user'
  get    '/index'  => 'login#welcome'
  get    '/signup/new' => 'login#signupnew', as: 'login_user_signup'
  post    '/signup' => 'login#signupcreate', as: 'create_login_user' 
  delete '/logout' => 'login#delete', as: 'logout_user'
  #login routes end

  #author routes start
  get '/authors' => 'authors#index'
  get '/authors/new' => 'authors#new',  as: 'new_author'
  post '/authors' => 'authors#create',   as: 'create_author'  
  get '/authors/:id' => 'authors#show', as: 'show_author'
  get '/authors/:id/edit' => 'authors#edit', as: 'edit_author'
  patch '/authors/:id' => 'authors#update', as: 'update_author'
  delete '/authors/:id' => 'authors#destroy', as: 'delete_author'
  #author routes end

  #quotes routes start
  get '/authors/:author_id/quotes' => 'quotes#index', as: 'authors_quotes'
  get '/authors/:author_id/quotes/new' => 'quotes#new',  as: 'new_author_quotes'
  post '/authors/:author_id/quotes' => 'quotes#create',  as: 'create_author_quotes' 
  get '/authors/:author_id/quotes/:id' => 'quotes#show', as: 'show_author_quotes'
  get '/authors/:author_id/quotes/:id/edit' => 'quotes#edit', as: 'edit_author_quotes'
  patch '/authors/:author_id/quotes/:id' => 'quotes#update', as: 'update_author_quotes'
  delete '/authors/:author_id/quotes/:id' => 'quotes#destroy', as: 'delete_author_quotes'
  #quotes routes end

  #tag routes start
  get '/tag' => 'tags#index', as: 'tag'
  get '/tag/new' => 'tags#new',  as: 'new_tag'
  post '/tag' => 'tags#create',  as: 'create_tag' 
  get '/tag/:id' => 'tags#show', as: 'show_tag'
  get '/tag/:id/edit' => 'tags#edit', as: 'edit_tag'
  patch '/tag/:id' => 'tags#update', as: 'update_tag'

  delete '/tag/:id' => 'tags#destroy', as: 'delete_tag'
  #tag routes end

end

app/models/author.rb
class Author < ApplicationRecord
    has_many :quote, dependent: :destroy

    validates :author_name, presence:true  
    validates :author_name, uniqueness:true
end

app/controllers/authors_controller.rb
class AuthorsController < ApplicationController
    before_action :require_login
    def index
        @author = Author.all
    end

    def new
        @author = Author.new
    end

    def create
        @author = Author.create(params.require(:author).permit(:author_name))
        if @author.save
            redirect_to authors_path
            puts @author
        else
            flash[:errors] = @author.errors.full_messages 
            redirect_to new_author_url    
        end
    end

    def show
        @author = Author.find(params[:id])
    end 

    def edit
        @author = Author.find(params[:id])
    end 

    def update
        @author = Author.find(params[:id])

        if @author
            @author.update(params.permit(:author_name))
            redirect_to authors_path
        else
            flash[:errors] = @author.errors.full_messages 
            redirect_to edit_author_url
        end 
    end 

    def destroy
        @author = Author.find(params[:id])
        if @author
            @author.destroy
            redirect_to authors_path
        end 
    end 

end

app/helpers/authors_helper.rb
module AuthorsHelper
end

app/views/authors/edit.html.erb
<h1> Edit Author</h1>


<% if flash[:errors]%>
    <% flash[:errors].each do |error| %>
            <p style="color: red"><%= error%></p>
    <% end %>
<%end%>


   <%= form_tag update_author_path(@author), method: :patch do  %>
  
        <%= label_tag :authorname%>
        
        <%= text_field_tag :author_name, @author.author_name %>
        
   <%= submit_tag "Update"%>
<%end%>

app/views/authors/index.html.erb
<%= stylesheet_link_tag "authors", media: "all", "data-turbolinks-track" => "reload" %>
 
  <div class="container-fluid p-0"> 
        <div class="row" id="body-row">
            <div id="sidebar-container" class="sidebar-expanded d-none d-md-block">
                <ul class="list-group">
                    <li class="list-group-item sidebar-separator-title text-muted d-flex align-items-center menu-collapsed">
                        <small>MAIN MENU</small>
                    </li>
                    <a href="#submenu1" data-toggle="collapse" aria-expanded="false" class="bg-dark list-group-item list-group-item-action flex-column align-items-start">
                        <div class="d-flex w-100 justify-content-start align-items-center">
                            <span class="icon">
                            <i class="fas fa-list-alt mr-3"></i>
                            </span> 
                            <span class="menu-collapsed">Dashboard</span>
                            <span class="submenu-icon ml-auto"></span>
                        </div>
                    </a>
                      <div id='submenu1' class="collapse sidebar-submenu">
                        <a data-toggle="list" href="#home" class="list-group-item list-group-item-action bg-dark text-white">
                            <span class="menu-collapsed"> <i class="fas fa-users mr-3"></i>Authors Section</span>
                        </a>
                        <a data-toggle="list" href="#profile" class="list-group-item list-group-item-action bg-dark text-white">
                            <span class="menu-collapsed"> <i class="fas fa-code mr-3"> </i>Basic Programming</span>
                        </a>
                    </div>
                    <a class="bg-dark list-group-item list-group-item-action flex-column align-items-start">
                        <div class="d-flex w-100 justify-content-start align-items-center">
                            <span class="icon">
                              <i class="fas fa-power-off"></i>
                            </span> 
                                <%= button_to  "Log Out", logout_user_path,class: "btn btn-link menu-collapsed" ,method: :delete%>
                        </div>
                    </a>
                </ul>
            </div><!-- sidebar-container end -->

            <!--  side bar content start --> 
            <div class="col">
                <div class="tab-content">
                    <div class="tab-pane active" id="home" role="tabpanel">
                    <div class="jumbotron">
                      <h1 class="display-4">Authors Section</h1>
                      <p class="lead">Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.</p>
                      <p>Ut enim ad minim veniam,quis nostrud exercitation ullamco laboris nisi ut. </p>                      
                          <% if is_admin? %>
                            <%= button_to  "Add Author",new_author_path, :class => "btn btn-primary btn-md",method: :get%>   
                          <% end %>
                    </div>

                      <table class="table table-striped">
                        <thead>
                          <tr>
                            <th scope="col">author_id</th>
                            <th scope="col">Author Name</th>
                            <th scope="col">Quotes</th>
                             <% if is_admin? %>
                                 <th scope="col">Action</th>
                            <%end%>
                          </tr>
                        </thead>
                        <tbody>
                          <% @author.each do |author| %>
                          <tr>
                            <th scope="row"><%= author.id%></th>
                            <td><%=  author.author_name %></td>
                            <td><%= link_to "Show Quotes", authors_quotes_path(author), method: :get%></td>
                                <% if is_admin? %>
                            <td><%= link_to "Show Details",show_author_url(author)%></td>
                            <td>
                                  <span class="del-btn">
                                      <%= link_to "x", delete_author_path(author), :class => "del-btn" ,method: :delete%> 
                                  </span>
                            </td>
                               <% end %> 
                          </tr>
                          <%end%>
                        </tbody>
                      </table>
                    </div>
                    <div class="tab-pane" id="profile" role="tabpanel">Lorem ipsum dolor sit amet consectetur adipisicing elit. Ad sint dolorem error quasi nam reprehenderit ut delectus eum dolores! Dignissimos?</div>
                </div>          
        </div><!-- content end -->

app/views/authors/new.html.erb
<% if flash[:errors]%>
    <% flash[:errors].each do |error| %>
        <div class="alert alert-danger" role="alert">
                <%= error%>
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                <span aria-hidden="true">&times;</span>
            </button>
        </div>
    <% end %>
<%end%>

<div class="container mt-5 mr-5">
    <div class="col-md-6 mb-4">
        <div class="card">
            <div class="card-body">
                 <%= form_for @author do|f|%>
                         <h3 class="text-center font-bold py-4"><strong>Add New Author</strong></h3>
                                <div class="input-group mb-3">
                                        <div class="input-group-prepend">
                                             <span class="input-group-text" id="inputGroup-sizing-default"><i class="fas fa-user"></i></span>
                                        </div>
                                            <%= f.text_field  :author_name, placeholder: "Enter Author Name",class: "form-control" %>                  
                                </div>
                                <div class="text-center py-4">
                                    <%= f.submit "Create Author", class: "btn btn-primary" %>
                                </div>
                 <%end%>                       
            </div>
        </div>
    </div>
</div>

app/views/authors/show.html.erb
<% if flash[:errors]%>
    <% flash[:errors].each do |error| %>
        <div class="alert alert-danger" role="alert">
                <%= error%>
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                <span aria-hidden="true">&times;</span>
            </button>
        </div>
    <% end %>
<%end%>
 
<div class="container mt-5 mr-5">
    <div class="col-md-6 mb-4">
        <div class="card">
            <div class="card-body">
                <%= form_tag update_author_path(@author), method: :patch do  %>
                         <h3 class="text-center font-bold py-4"><strong>Edit Author</strong></h3>
                            <div class="input-group mb-3">
                                    <div class="input-group-prepend">
                                          <span class="input-group-text" id="inputGroup-sizing-default"><i class="fas fa-user"></i></span>
                                    </div>  
                                    <%= text_field_tag  :author_name,  @author.author_name,class: "form-control" %>                  
                            </div>
                            <div class="text-center py-4">
                                <%= submit_tag "Update Author", class: "btn btn-primary" %>
                            </div>
                 <%end%>                       
            </div>
        </div>
    </div>
</div>