config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  
  #root route
  root   'login#welcome'

  # user route start
  get '/users', to: 'users#index'
  get '/users/new' => 'users#new', as: 'new_user'
  post '/users'    => 'users#create', as: 'create_user'
  get  '/users/:id' => 'users#show', as: 'show_user'
  get '/users/:id/edit ' => 'users#edit', as: 'edit_user'
  patch '/users/:id'   => 'users#update', as: 'update_user'
  delete '/users/:id' => 'users#destroy', as: 'delete_user'
  # user route end

  #login routes start
  get    '/login'  => 'login#new'
  post   '/login'  => 'login#create', as: 'login_user'
  get    '/index'  => 'login#welcome'
  get    '/signup/new' => 'login#signupnew', as: 'login_user_signup'
  post    '/signup' => 'login#signupcreate', as: 'create_login_user' 
  delete '/logout' => 'login#delete', as: 'logout_user'
  #login routes end

  #author routes start
  get '/authors' => 'authors#index'
  get '/authors/new' => 'authors#new',  as: 'new_author'
  post '/authors' => 'authors#create',   as: 'create_author'  
  get '/authors/:id' => 'authors#show', as: 'show_author'
  get '/authors/:id/edit' => 'authors#edit', as: 'edit_author'
  patch '/authors/:id' => 'authors#update', as: 'update_author'
  delete '/authors/:id' => 'authors#destroy', as: 'delete_author'
  #author routes end

  #quotes routes start
  get '/authors/:author_id/quotes' => 'quotes#index', as: 'authors_quotes'
  get '/authors/:author_id/quotes/new' => 'quotes#new',  as: 'new_author_quotes'
  post '/authors/:author_id/quotes' => 'quotes#create',  as: 'create_author_quotes' 
  get '/authors/:author_id/quotes/:id' => 'quotes#show', as: 'show_author_quotes'
  get '/authors/:author_id/quotes/:id/edit' => 'quotes#edit', as: 'edit_author_quotes'
  patch '/authors/:author_id/quotes/:id' => 'quotes#update', as: 'update_author_quotes'
  delete '/authors/:author_id/quotes/:id' => 'quotes#destroy', as: 'delete_author_quotes'
  #quotes routes end

  #tag routes start
  get '/tag' => 'tags#index', as: 'tag'
  get '/tag/new' => 'tags#new',  as: 'new_tag'
  post '/tag' => 'tags#create',  as: 'create_tag' 
  get '/tag/:id' => 'tags#show', as: 'show_tag'
  get '/tag/:id/edit' => 'tags#edit', as: 'edit_tag'
  patch '/tag/:id' => 'tags#update', as: 'update_tag'

  delete '/tag/:id' => 'tags#destroy', as: 'delete_tag'
  #tag routes end

end

app/models/user.rb
class User < ApplicationRecord

has_secure_password

validates :username, presence:true  
validates :username, uniqueness:true
validates :email, presence: true 
validates :email, format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i,
               message: "Email invalid"  },uniqueness: { case_sensitive: false },
               length: { minimum: 4, maximum: 254 }
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
   before_action :require_login,  only:[:show, :update, :destroy]
    
    def index
        @users = User.all
    end

    def new
        @user = User.new
    end    

    def create
        @user = User.create(params.require(:user).permit(:email, :username, :password))

        if @user.save                  
            redirect_to '/users' 

        else
            flash[:errors] = @user.errors.full_messages 
            redirect_to new_user_url    
        end
    end 
    

    def show
         @users = User.find(params[:id])
        if  @users == current_user 
                @users
        else  
            flash[:errors] = @users.errors.full_messages 
            redirect_to '/users'
        end   
    end 

    def edit
        @user = User.find(params[:id])
        if  @user == current_user || is_admin?
            @user
        else  
             flash[:alert] = @user.errors.full_messages 
            redirect_to '/users' 
        end   
    end
    
    def update
        @user = User.find(params[:id])
        if @user
            @user.update(params.permit(:username, :email, :password))
            redirect_to '/users'
        else
            flash[:errors] = @user.errors.full_messages 
            redirect_to edit_user_url
        end
    end 

    def destroy
        @user = User.find(params[:id])
        @user.destroy
        redirect_to users_path
    end 
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/edit.html.erb
<% if flash[:errors]%>
    <% flash[:errors].each do |error| %>
        <div class="alert alert-danger" role="alert">
                <%= error%>
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                <span aria-hidden="true">&times;</span>
            </button>
        </div>
    <% end %>
<%end%>
 
<div class="container mt-5 mr-5">
    <div class="col-md-6 mb-4">
        <div class="card">
            <div class="card-body">
                <%= form_tag update_user_path(@user), method: :patch do  %>
                         <h3 class="text-center font-bold py-4"><strong>Edit User</strong></h3>
                            <div class="input-group mb-3">
                                    <div class="input-group-prepend">
                                          <span class="input-group-text" id="inputGroup-sizing-default"><i class="fas fa-user"></i></span>
                                    </div>  
                                    <%= text_field_tag  :username,  @user.username,class: "form-control" %>                  
                            </div>

                            <div class="input-group mb-3">
                                    <div class="input-group-prepend">
                                          <span class="input-group-text" id="inputGroup-sizing-default"><i class="fas fa-envelope"></i></span>
                                    </div>  
                                    <%= text_field_tag  :email,  @user.email ,class: "form-control" %>                  
                            </div>
                            <div class="text-center py-4">
                                <%= submit_tag "Update user", class: "btn btn-primary" %>
                            </div>
                 <%end%>                       
            </div>
        </div>
    </div>
</div>

app/views/users/index.html.erb
 <% if flash[:alert]%>
        <div class="alert alert-warning" role="alert">
                <%=  flash[:alert] = "Invalid Action!"%>
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                <span aria-hidden="true">&times;</span>
            </button>
        </div>
<%end%>
 
 
  <div class="container-fluid p-0"> 
        <div class="row" id="body-row">
            <div id="sidebar-container" class="sidebar-expanded d-none d-md-block">
                <ul class="list-group">
                    <li class="list-group-item sidebar-separator-title text-muted d-flex align-items-center menu-collapsed">
                        <small>MAIN MENU</small>
                    </li>
                    <a href="#submenu1" data-toggle="collapse" aria-expanded="false" class="bg-dark list-group-item list-group-item-action flex-column align-items-start">
                        <div class="d-flex w-100 justify-content-start align-items-center">
                            <span class="icon">
                            <i class="fas fa-list-alt mr-3"></i>
                            </span> 
                            <span class="menu-collapsed">Dashboard</span>
                            <span class="submenu-icon ml-auto"></span>
                        </div>
                      </a>
                          <div id='submenu1' class="collapse sidebar-submenu">
                              <a data-toggle="list" href="#home" class="list-group-item list-group-item-action bg-dark text-white">
                                  <span class="menu-collapsed"> <i class="fas fa-users mr-3"></i>Users Section</span>
                              </a>
                         </div>
                  
  
                    <a class="bg-dark list-group-item list-group-item-action flex-column align-items-start">
                        <div class="d-flex w-100 justify-content-start align-items-center">
                            <span class="icon">
                              <i class="fas fa-power-off"></i>
                            </span> 
                                <%= button_to  "Log Out", logout_user_path,class: "btn btn-link menu-collapsed" ,method: :delete%>
                        </div>
                    </a>

  

                  
                        
                </ul>
            </div><!-- sidebar-container end -->
          <!--  side bar content start --> 
            <div class="col">
                <div class="tab-content">
                    <div class="tab-pane active" id="home" role="tabpanel">
                    <div class="jumbotron">
                      <h1 class="display-2">Users Section</h1>
                       <% if logged_in? %>
                           <p class="display-4"> You are logged in as, <%= current_user.username%></p>
                        <%end%>
                      <p>Ut enim ad minim veniam,quis nostrud exercitation ullamco laboris nisi ut. </p>                      
                          <% if is_admin? %>
                             <%= button_to  "Add New User",new_user_path, :class => "btn btn-primary btn-md",method: :get%>   
                          <% end %>
                    </div>

                      <table class="table table-striped">
                        <thead>
                          <tr>
                            <th scope="col">user_id</th>
                            <th scope="col">UserName</th>
                            <th scope="col">Action</th>
                          </tr>
                        </thead>
                        <tbody>
                            <% @users.each do |user| %>
                          <tr>
                            <th scope="row"><%= user.id%></th>
                            <td><%=  user.username %></li></td>
                            <td><%= link_to "Show Details", edit_user_path(user)%></td>
                            <td>
                              <% if is_admin? %>
                                    <span class="del-btn">
                                        <%= link_to "x", delete_user_path(user), :class => "del-btn" ,method: :delete%> 
                                    </span>
                              <%end%>
                            </td>
                          </tr>
                          <%end%>
                        </tbody>
                      </table>
                    </div>
                    <div class="tab-pane" id="profile" role="tabpanel">Lorem ipsum dolor sit amet consectetur adipisicing elit. Ad sint dolorem error quasi nam reprehenderit ut delectus eum dolores! Dignissimos?</div>
                </div>          
        </div><!-- content end -->

app/views/users/new.html.erb
<% if flash[:errors]%>
    <% flash[:errors].each do |error| %>
        <div class="alert alert-danger" role="alert">
                <%= error%>
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                <span aria-hidden="true">&times;</span>
            </button>
        </div>
    <% end %>
<%end%>

<div class="container mt-5 mr-5">
    <div class="col-md-6 mb-4">
        <div class="card">
            <div class="card-body">
                    <%= form_for @user do|f|%>
                         <h3 class="text-center font-bold py-4"><strong>Register New User</strong></h3>
                                <div class="input-group mb-3">
                                        <div class="input-group-prepend">
                                             <span class="input-group-text" id="inputGroup-sizing-default"><i class="fas fa-envelope"></i></span>
                                        </div>
                                               <%= f.text_field  :email, placeholder: "Enter email",class: "form-control" %>                  
                                </div>
                                <div class="input-group mb-3">
                                        <div class="input-group-prepend">
                                             <span class="input-group-text" id="inputGroup-sizing-default"><i class="fas fa-user"></i></i></span>
                                        </div>
                                               <%= f.text_field  :username, placeholder: "Enter Username",class: "form-control" %>                  
                                </div>
                                <div class="input-group mb-3">
                                        <div class="input-group-prepend">
                                             <span class="input-group-text" id="inputGroup-sizing-default"><i class="fas fa-lock"></i></i></span>
                                        </div>
                                               <%= f.password_field  :password, placeholder: "Enter password",class: "form-control" %>                  
                                </div>
                                <div class="text-center py-4">
                                    <%= f.submit "Register", class: "btn btn-primary" %>
                                </div>
                 <%end%>                       
            </div>
        </div>
    </div>
</div>

app/views/users/show.html.erb
<h1>Show User Page</h1>


<%= button_to "Edit User", edit_user_path(@users), method: :get%>

<h2>Name <%= @users.username %></h2>
<h2>email <%= @users.email %></h2>
<h2>password <%= @users.password %></h2>


<%= button_to "Delete user", delete_user_path(@users), method: :delete%>


 <%= button_to  "Sign Up", new_user_path, method: :get%>   

 <%= button_to  "Log In", '/login', method: :get%>   

 <%= button_to  "Log Out",logout_user_path, method: :delete%>   