config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  
  #root route
  root   'login#welcome'

  # user route start
  get '/users', to: 'users#index'
  get '/users/new' => 'users#new', as: 'new_user'
  post '/users'    => 'users#create', as: 'create_user'
  get  '/users/:id' => 'users#show', as: 'show_user'
  get '/users/:id/edit ' => 'users#edit', as: 'edit_user'
  patch '/users/:id'   => 'users#update', as: 'update_user'
  delete '/users/:id' => 'users#destroy', as: 'delete_user'
  # user route end

  #login routes start
  get    '/login'  => 'login#new'
  post   '/login'  => 'login#create', as: 'login_user'
  get    '/index'  => 'login#welcome'
  get    '/signup/new' => 'login#signupnew', as: 'login_user_signup'
  post    '/signup' => 'login#signupcreate', as: 'create_login_user' 
  delete '/logout' => 'login#delete', as: 'logout_user'
  #login routes end

  #author routes start
  get '/authors' => 'authors#index'
  get '/authors/new' => 'authors#new',  as: 'new_author'
  post '/authors' => 'authors#create',   as: 'create_author'  
  get '/authors/:id' => 'authors#show', as: 'show_author'
  get '/authors/:id/edit' => 'authors#edit', as: 'edit_author'
  patch '/authors/:id' => 'authors#update', as: 'update_author'
  delete '/authors/:id' => 'authors#destroy', as: 'delete_author'
  #author routes end

  #quotes routes start
  get '/authors/:author_id/quotes' => 'quotes#index', as: 'authors_quotes'
  get '/authors/:author_id/quotes/new' => 'quotes#new',  as: 'new_author_quotes'
  post '/authors/:author_id/quotes' => 'quotes#create',  as: 'create_author_quotes' 
  get '/authors/:author_id/quotes/:id' => 'quotes#show', as: 'show_author_quotes'
  get '/authors/:author_id/quotes/:id/edit' => 'quotes#edit', as: 'edit_author_quotes'
  patch '/authors/:author_id/quotes/:id' => 'quotes#update', as: 'update_author_quotes'
  delete '/authors/:author_id/quotes/:id' => 'quotes#destroy', as: 'delete_author_quotes'
  #quotes routes end

  #tag routes start
  get '/tag' => 'tags#index', as: 'tag'
  get '/tag/new' => 'tags#new',  as: 'new_tag'
  post '/tag' => 'tags#create',  as: 'create_tag' 
  get '/tag/:id' => 'tags#show', as: 'show_tag'
  get '/tag/:id/edit' => 'tags#edit', as: 'edit_tag'
  patch '/tag/:id' => 'tags#update', as: 'update_tag'

  delete '/tag/:id' => 'tags#destroy', as: 'delete_tag'
  #tag routes end

end

app/models/tag.rb
class Tag < ApplicationRecord
    has_many  :quotation_tags, dependent: :destroy
    has_many  :quotes,:through =>  :quotation_tags   
    
    validates :name, presence: true, 
              length: {minimum: 4}
    
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
    def index
        @tags = Tag.all
    end 

    def  new
        @tag = Tag.new
    end
    
    def create
        @tag = Tag.create(params.permit(:name))
        if @tag.save
            redirect_to tag_path
        else    
            redirect_to create_tag_path
        end

    end
    
    def show
        @tag = Tag.find_by(params[:id])
    end

    def edit
        @tag = Tag.find(params[:id])
    end

    def update
        @tag = Tag.find(params[:id])
        if @tag
            @tag.update(params.permit(:name))
            redirect_to tag_path
        else
            redirect_to update_tag_path
        end
    end

    def destroy
        @tag = Tag.find(params[:id])
        if @tag
            @tag.destroy
            redirect_to tag_path
        else
            redirect_to tag_path
        end
    end    
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/views/tags/edit.html.erb
<% if flash[:errors]%>
    <% flash[:errors].each do |error| %>
        <div class="alert alert-danger" role="alert">
                <%= error%>
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                <span aria-hidden="true">&times;</span>
            </button>
        </div>
    <% end %>
<%end%>

<div class="container mt-5 mr-5">
    <div class="col-md-6 mb-4">
        <div class="card">
            <div class="card-body">
                    <%= form_tag update_tag_path(@tag), method: :patch do %>
                    <h3 class="text-center font-bold py-4"><strong>Edit tag</strong></h3>
                            <div class="input-group mb-3">
                                    <div class="input-group-prepend">
                                          <span class="input-group-text" id="inputGroup-sizing-default"><i class="fas fa-pen"></i></span>
                                    </div>  
                                    <%= text_field_tag  :name, @tag.name ,class: "form-control" %>                  
                            </div>

                            <div class="text-center py-4">
                                <%= submit_tag "Update Tag", class: "btn btn-primary"%>
                            </div>
                 <%end%>                       
            </div>
        </div>
    </div>
</div>

app/views/tags/index.html.erb
<%= stylesheet_link_tag "authors", media: "all", "data-turbolinks-track" => "reload" %>

<% if flash[:errors]%>
        <div class="alert alert-warning" role="alert">
                <%= flash[:errors] = "You are not Authorized to that!"%>
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                <span aria-hidden="true">&times;</span>
            </button>
        </div>
<%end%>
 
  <div class="container-fluid p-0"> 
        <div class="row" id="body-row">
            <div id="sidebar-container" class="sidebar-expanded d-none d-md-block">
                <ul class="list-group">
                    <li class="list-group-item sidebar-separator-title text-muted d-flex align-items-center menu-collapsed">
                        <small>MAIN MENU</small>
                    </li>
                    <a href="#submenu1" data-toggle="collapse" aria-expanded="false" class="bg-dark list-group-item list-group-item-action flex-column align-items-start">
                        <div class="d-flex w-100 justify-content-start align-items-center">
                            <span class="icon">
                            <i class="fas fa-list-alt mr-3"></i>
                            </span> 
                            <span class="menu-collapsed">Dashboard</span>
                            <span class="submenu-icon ml-auto"></span>
                        </div>
                      </a>
                          <div id='submenu1' class="collapse sidebar-submenu">
                              <a data-toggle="list" href="#home" class="list-group-item list-group-item-action bg-dark text-white">
                                  <span class="menu-collapsed"> <i class="fas fa-users mr-3"></i>Tag Section</span>
                              </a>

                         </div>
                    <a class="bg-dark list-group-item list-group-item-action flex-column align-items-start">
                        <div class="d-flex w-100 justify-content-start align-items-center">
                            <span class="icon">
                              <i class="fas fa-power-off"></i>
                            </span> 
                                <%= button_to  "Log Out", logout_user_path,class: "btn btn-link menu-collapsed" ,method: :delete%>
                        </div>
                    </a>

                </ul>
            </div><!-- sidebar-container end -->
            <div class="col">
                <div class="tab-content">
                    <div class="tab-pane active" id="home" role="tabpanel">

                <div class="jumbotron">
                    <h1 class="display-4">Tag Section</h1>
                    <p class="lead">Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.</p>
                    <p>Ut enim ad minim veniam,quis nostrud exercitation ullamco laboris nisi ut. </p>                      
                        <% if is_admin? %> 
                            <%= button_to  "Add New Tag",new_tag_path,  :class => "btn btn-primary btn-md",method: :get%>   
                        <%end%>
                </div>

                <table class="table table-striped">
                        <thead>
                          <tr>
                            <th scope="col">tag_id</th>
                            <th scope="col">Tag Name</th>
                             <% if is_admin? %>
                            <th scope="col">Action</th>
                            <%end%>
                          </tr>
                        </thead>
                        <tbody>
                            <% @tags.each do |tag| %>
                          <tr>
                            <th scope="row"><%= tag.id%></th>
                            <td><%=  tag.name %></td>
                                <% if is_admin? %>
                            <td><%= link_to "Show Details",edit_tag_path(tag)%></td>
                            <td>
                                  <span class="del-btn">
                                      <%= link_to "x", delete_tag_path(tag), :class => "del-btn" ,method: :delete%> 
                                  </span>
                            </td>
                               <% end %> 
                          </tr>
                          <%end%>
                        </tbody>
                      </table>
                </div>          
        </div><!-- content end -->

app/views/tags/new.html.erb
<% if flash[:errors]%>
    <% flash[:errors].each do |error| %>
        <div class="alert alert-danger" role="alert">
                <%= error%>
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                <span aria-hidden="true">&times;</span>
            </button>
        </div>
    <% end %>
<%end%>

<div class="container mt-5 mr-5">
    <div class="col-md-6 mb-4">
        <div class="card">
            <div class="card-body">
                 <%= form_tag create_tag_path do %>
                         <h3 class="text-center font-bold py-4"><strong>Create New Tag</strong></h3>
                                <div class="input-group mb-3">
                                        <div class="input-group-prepend">
                                             <span class="input-group-text" id="inputGroup-sizing-default"><i class="fas fa-user"></i></span>
                                        </div>
                                            <%= text_field_tag  :name, "Enter Tag...",class: "form-control" %>                  
                                </div>
                                <div class="text-center py-4">
                                    <%= submit_tag "Create Tag", class: "btn btn-primary" %>
                                </div>
                 <%end%>                       
            </div>
        </div>
    </div>
</div>

app/views/tags/show.html.erb
<h1>Show Tag Page</h1>


<%= button_to "Edit Quotes", edit_tag_path(@tag), method: :get%>

<h2>Tag Name <%= @tag.name %></h2>

 <%= button_to "Delete Tag", delete_tag_path(@tag), method: :delete%>